export const LoadingBar: string;
export const Logo: string;
export const Slider: string;
export const Line: string;
export const Subline: string;
export const Inc: string;
export const increase: string;
export const Dec: string;
export const decrease: string;
