export const Information: string;
export const InformationContent: string;
export const InformationTitle: string;
export const Title: string;
export const RightMenu: string;
export const MenuItem: string;
export const InformationData: string;
export const TabTable: string;
export const NavTab: string;
