export const OrderInfo: string;
export const OrderInfoDialog: string;
export const ModalBody: string;
export const OrderInfoTable: string;
export const OrderInfoTitle: string;
export const OrderLog: string;
export const OrderLogTitle: string;
export const OrderLogTable: string;
export const CloseButton: string;
