export const PositionStatement: string;
export const TabTable: string;
export const TabContent: string;
export const PositionStatementTab: string;
export const PositionStatementFilter: string;
export const AccountDropdown: string;
export const PositionStatementQuery: string;
export const PositionStatementBoard: string;
export const SheetData: string;
