export const Account: string;
export const AccountContent: string;
export const AccountTitle: string;
export const Title: string;
export const RightMenu: string;
export const MenuItem: string;
export const AccountData: string;
export const TabTable: string;
export const NavTab: string;
