declare module 'i18next-chained-backend';
declare module 'i18next-localstorage-backend';
declare module 'socketcluster-client';
declare module 'sc-codec-min-bin';
declare module 'react-block-ui/redux';
declare module 'react-block-ui/reduxMiddleware';
declare module 'react-select-fast-filter-options';
declare module 'react-public-ip';
declare module '@kartikag01/react-custom-scrollbars';
